import Head from 'next/head'
import Navbar from './components/Navbar'
import DivOne from './components/DivOne'
// import LinkNMemoji from './components/LinkNMemoji'

export default function Home() {
  return (
    <>
      <Head>
        <title>Aarya's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white-10 px-0 font-typewriter'>

        <section className=" min-h-screen p-5">

          {/* navbar './components/Navbar' */}
          <Navbar />
<br />
<br />
<br />
          {/* landing page content, a brief intro 'bout my self */}
          <DivOne/>
      {/* <LinkNMemoji/> */}
        </section>

      </main>
    </>
  )
}
